In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("proj3.ipynb")

# Project 3: Data Transformation

## Due Date: Friday 10/28, 11:59 PM

## Assignment Details

In this project, we'll be working with one month of data from sensors in buildings at UC Berkeley. This is a very typical real-world dataset---i.e. it's kind of a mess. The full dataset contains a giant `data` table of sensor readings that is many billions of readings over the course of a decade; we will look at a single month of that data. It also contains a variety of other tables that contextualize the readings.

The schema for the database is shown below. Sometimes people think that if the data is a nice schema, then it's ready to go! We'll see about that.

**Note:** Each line represents a relationship between the two fields. The side of the line diverging to three lines / arrows suggests the "many" side of the relationship, while the side of the line converging to one arrow suggests the "one" side of the relationship.

<img src="data/schema.png">

## Logistics & Scoring Breakdown

For Data 101 students, this project is worth 15% of your grade. For Info 258 students, this project is worth 12% of your grade.

Each coding question has **both public tests and hidden tests**. Roughly 50% of your coding grade will be made up of your score on the public tests released to you, while the remaining 50% will be made up of unreleased hidden tests. Free-response questions will be manually graded.

This is an **individual project**. However, you’re welcome to collaborate with any other student in the class as long as it’s within the academic honesty guidelines.

Question | Points
--- | ---
1a	| 1
1b  | 1
1c	| 1
1d	| 2
2a	| 3
2b	| 1
3a	| 0
3b	| 1
3c	| 1
3d  | 0
3e  | 2
4a	| 2
4b	| 2
4c	| 3
**Total** | 20

In [2]:
# Run this cell to set up imports
import numpy as np
import pandas as pd

In [3]:
%reload_ext sql
%sql postgresql://jovyan@127.0.0.1:5432/template1

## Loading Up the Database
To load the database, run the following cell.

**IMPORTANT NOTE:** In contrary to previous projects, the database does not reload automatically upon running the following loading cell. If you would like to reload the database (e.g. if your database is modified in undesirable ways), **first restart the kernel**, and then run `!psql -h localhost -c 'DROP DATABASE IF EXISTS ucb_buildings'` in another cell **before** running the cell below.

In [4]:
import subprocess
import os
import warnings

call = subprocess.run(["psql", "-h", "localhost", \
                       "-tAc", "SELECT 1 FROM pg_database WHERE datname='ucb_buildings'", "template1"], \
                      stdout=subprocess.PIPE, text=True)

if call.stdout != "1\n":
    print("Loading database...")
    os.system("gunzip -c data/proj3.sql.gz | psql -h localhost -d template1 -f -")
else:
    print("Database was previously loaded.")

Database was previously loaded.

Now, run the following cell to connect to the `ucb_buildings` database. There should be no errors after running the following cell.

In [5]:
%sql postgresql://jovyan@127.0.0.1:5432/ucb_buildings

Run the following cell for grading purposes.

In [6]:
!mkdir -p results

<!-- BEGIN QUESTION -->

## Question 1: Unboxing the Data

### Question 1a

Note that the `data` table, in the full database, is billions of rows. What do you notice about the design of the database schema that helps support the large amount of data?

**Hint:** There is no need to examine any data here. What is a technique learned in [lecture 15](https://docs.google.com/presentation/d/1GogwyAylHrJoxer_apIkgnWDqC9LxTQ8/edit)? Define that technique.

<!--
BEGIN QUESTION
name: q1a
manual: true
points: 1
-->

The process of normalization, which splits relations into multiple relations to minimize duplicates (primary keys) to sepearte out fields and delete anomalies, helps support the large amount of data.

<!-- END QUESTION -->



### Question 1b

The diagram claims that `buildings_site_mapping` has a many-to-many relationship with `real_estate_metadata`. Let's validate that. 

Below is an example of `json_agg` being used with a table; you will need to do this in the next two parts.

In [7]:
%%sql
SELECT b.site, json_agg(b) from buildings_site_mapping b GROUP BY b.site LIMIT 5;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
5 rows affected.

[('Sutardja Dai Hall', [{'site': 'Sutardja Dai Hall', 'building': 'SUTARDJA DAI'}]),
 ('Le Conte Hall', [{'site': 'Le Conte Hall', 'building': 'LE CONTE'}]),
 ('Hildebrand Hall', [{'site': 'Hildebrand Hall', 'building': 'HILDEBRA ND'}]),
 ('Stephens Hall', [{'site': 'Stephens Hall', 'building': 'STEPHENS'}]),
 ('2000 Carleton Street', [{'site': '2000 Carleton Street', 'building': 'CARLETO2 000'}])]

Find the **distinct** values of `buildings_site_mapping.building` that match multiple tuples in `real_estate_metadata.building_name`, and for each such value of `buildings_site_mapping.building` return the matches as JSON via `json_agg(real_estate_metadata)`. Your output should contain the building and the `json_agg` in that order. Order your final result by building.

**Hint:** You should use a CTE to find the distinct buildings of `buildings_site_mapping` before applying necessary table joins.

In [8]:
%%sql result_1b <<
WITH distinct_building AS(
SELECT DISTINCT building
FROM buildings_site_mapping)

SELECT real_estate_metadata.building_name, json_agg(real_estate_metadata) 
FROM distinct_building 
INNER JOIN real_estate_metadata
ON distinct_building.building = real_estate_metadata.building_name
GROUP BY real_estate_metadata.building_name 
HAVING COUNT(real_estate_metadata.building_name) > 1
ORDER BY real_estate_metadata.building_name;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
5 rows affected.
Returning data to local variable result_1b

In [9]:
# Do not delete/edit this cell
result_1b.DataFrame().to_csv('results/result_1b.csv', index=False)

In [10]:
grader.check("q1b")

q1b results: All test cases passed!

### Question 1c

Now find examples of many matches in the opposite direction. For each distinct `real_estate_metadata.building_name` value, find the ones that have multiple matches in `buildings_site_mapping.building`, and for each return a `json_agg` of the multiple values for `buildings_site_mapping`. Your output should contain the building name and the `json_agg` in that order. Order your final result by building name.

**Hint:** You should use a CTE to find the distinct building names of `real_estate_metadata` before applying necessary table joins.

In [11]:
%%sql result_1c <<
WITH distinct_meta_building AS(
SELECT DISTINCT building_name
FROM real_estate_metadata)

SELECT buildings_site_mapping.building, json_agg(buildings_site_mapping) 
FROM distinct_meta_building 
INNER JOIN buildings_site_mapping
ON distinct_meta_building.building_name = buildings_site_mapping.building
GROUP BY buildings_site_mapping.building 
HAVING COUNT(buildings_site_mapping.building) > 1
ORDER BY buildings_site_mapping.building;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
4 rows affected.
Returning data to local variable result_1c

In [12]:
# Do not delete/edit this cell
result_1c.DataFrame().to_csv('results/result_1c.csv', index=False)

In [13]:
grader.check("q1c")

q1c results: All test cases passed!

<!-- BEGIN QUESTION -->

### Question 1d

Do you see any issues with the schema given? In particular, please address the two questions below:
- Can you uniquely determine the building given the sensor data? Why? (**Hint:** given a row in the `data` table, can you determine a **uniquely** associated row in `real_estate_metadata` table? Your answer should draw insights from 1b.)
- Could `buildings_site_mapping.building` be a valid foreign key pointing to `real_estate_metadata.building_name`? (**Hint:** think about the definition / constraints of a foreign key.)

<!--
BEGIN QUESTION
name: q1d
manual: true
points: 2
-->

You cannot uniquely determine the building given the sensor data, because for instance, if we look at result_1b; CAMPBELL is not only in Berkeley but also in LOS ANGELES, so there are multiple locations for a building. Also buildings_site_mapping.building could NOT be a valid foreign key pointing to real_estate_metadata.building_name, because real_estate_metadata.building_name is not unique, as there are duplicate names, hence not a valid primary key.

<!-- END QUESTION -->



## Question 2: Looking for Outliers in the Readings
Physical sensors like the ones generating this data are notorious for producing crazy outliers on occasion. In this section we'll do a little data cleaning of the outliers.

All the readings from all different kinds of sensors are mixed together in the `data` table. This hodgepodge of mixed readings is going to require us to do some extra work to look for outliers. Let's get started.

### Question 2a: Outlier Detection

Let's find the outlying values *for each sensor id*. We'll call something an outlier if it is **3 Hampel X84 intervals** away from the median. If 

Specifically, create a view `labeled_data` that contains all of the columns in `data` and adds three additional columns at the far right:
  - `median` containing the median using `percentile_disc`
  - `mad` containing the Median Absolute Deviation (MAD),
  - `outlier` that contains `true` for the outlier readings and `false` for the rest. **Also,** for data points where the mad is 0, set this to `false`.

In [14]:
%%sql
SELECT *
FROM data
LIMIT 10;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
10 rows affected.

[(datetime.datetime(2018, 6, 12, 23, 0, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65182.74),
 (datetime.datetime(2018, 6, 12, 22, 45, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65182.51),
 (datetime.datetime(2018, 6, 12, 22, 30, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65182.27),
 (datetime.datetime(2018, 6, 12, 22, 15, 10, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65182.02),
 (datetime.datetime(2018, 6, 12, 22, 0, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65181.77),
 (datetime.datetime(2018, 6, 12, 21, 45, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65181.54),
 (datetime.datetime(2018, 6, 12, 21, 30, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65181.3),
 (datetime.datetime(2018, 6, 12, 21, 15, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65181.04),
 (datetime.datetime(2018, 6, 12, 21, 0, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65180.8),
 (datetime.datetime(2018, 6, 12, 20, 45, 9, tzinfo=datetime.timezone.utc), 'a3d3326f-20ab-5f1d-97c7-f3084df43f06', 65180.57)]

In [15]:
%%sql result_2a <<
CREATE OR REPLACE VIEW labeled_data AS

WITH
medians AS
(SELECT id, percentile_disc(.5) WITHIN GROUP (ORDER BY value) AS median 
 FROM data
 GROUP BY id),

absdevs AS
(SELECT abs(value - median) as d, data.id, data.value, median
 FROM data 
 INNER JOIN medians ON data.id = medians.id),

stats AS
(SELECT percentile_disc(.5) WITHIN GROUP (ORDER BY d) as mad, id, median
FROM absdevs
GROUP BY id, median)

(SELECT d.*, s.median, s.mad, CASE 
     WHEN d.value NOT BETWEEN (median - 3*1.4826*s.mad) AND (median + 3*1.4826*s.mad) AND s.mad > 0 THEN true ELSE false 
     END AS outlier
FROM data d
INNER JOIN stats s ON d.id = s.id);

SELECT * FROM labeled_data WHERE outlier ORDER BY id, time LIMIT 100;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
Done.
100 rows affected.
Returning data to local variable result_2a

In [16]:
# Do not delete/edit this cell
result_2a.DataFrame().to_csv('results/result_2a.csv', index=False)

In [17]:
grader.check("q2a")

q2a results: All test cases passed!

### Question 2b: Outlier Handling (Winsorization)

In this step we'll define a view `cleaned_data` over all the columns of `labeled_data` and one additional column on the far right called `clean_value`. This column will contain a copy of `data.value` if that value is not an outlier. For outliers, it should contain the value Winsorized to the nearest outlier boundary value (3 Hampel X84 intervals from the median). If the MAD is 0, then the cleaned value should be the same as the original value.

In [18]:
%%sql
(SELECT MAX(l.value) AS winsor 
FROM labeled_data l
WHERE l.value < (l.median - 3*1.4826*l.mad));

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
1 rows affected.

[(498.32,)]

In [19]:
%%sql result_2b <<
CREATE OR REPLACE VIEW cleaned_data AS


SELECT l.*, CASE
    WHEN l.value > (l.median + 3*1.4826*l.mad) THEN (l.median + 3*1.4826*l.mad) 
    WHEN l.value < (l.median - 3*1.4826*l.mad) THEN (l.median - 3*1.4826*l.mad)
    ELSE l.value
    END AS clean_value
FROM labeled_data l;

SELECT * FROM cleaned_data WHERE outlier ORDER BY id, time LIMIT 100;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
Done.
100 rows affected.
Returning data to local variable result_2b

In [20]:
# Do not delete/edit this cell
result_2b.DataFrame().to_csv('results/result_2b.csv', index=False)

In [21]:
grader.check("q2b")

q2b results: All test cases passed!

<!-- BEGIN QUESTION -->

## Question 3: Entity Resolution

### Question 3a
There is a lot of mess in this dataset related to entity names. As a start, have a look at all of the distinct values in the `units` field of the `metadata` table. What do you notice about these values? Are there any duplicates?

<!--
BEGIN QUESTION
name: q3a
manual: true
points: 0
-->

I notice that there are a lot of duplicates for the same unit types, such as Gal vs. gal and KWH vs. Kwh. Even if we select distinct values, the different capitlization of the same unit showed up.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

### Question 3b

Sometimes, entity resolution is as simple as a text transformation. For example, how many unique `units` values are there, and how many would there be if we ignored case (upper vs. lower case)? Your output should be a table with one row and two columns; the first column should contain the number of unique `units` values, and the second column should contain the number of unique `units` values if we ignored case. The two columns can have arbitrary names.

<!--
BEGIN QUESTION
name: q3bm
manual: true
points: 0
-->

In [22]:
%%sql result_3b <<
SELECT COUNT(DISTINCT units), COUNT(DISTINCT UPPER(units)) 
FROM metadata;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
1 rows affected.
Returning data to local variable result_3b

<!-- END QUESTION -->

<!--
BEGIN QUESTION
name: q3b
points: 1
-->

In [23]:
# Do not delete/edit this cell
result_3b.DataFrame().to_csv('results/result_3b.csv', index=False)

In [24]:
grader.check("q3b")

q3b results: All test cases passed!

<!-- BEGIN QUESTION -->

### Question 3c

Arguably we shouldn't care about these alternative unit labels, *as long as each sensor class uses a single value of `units` for all its sensor ids*. After all, maybe the capitalization means something to somebody!

Write a SQL query that returns single row with one column of value `true` if the condition in italics above holds, or a single row with one column of value `false` otherwise. Please do not hard code this query - we reserve the right to penalize your score if you do so.

<!--
BEGIN QUESTION
name: q3cm
manual: true
points: 0
-->

In [25]:
%%sql 
SELECT class, COUNT(DISTINCT(units))
FROM metadata
GROUP BY class;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
1227 rows affected.

[('225 KVA Xfmr - Panel LNDB-2 Demand (kW)', 1),
 ('225 KVA Xfmr - Panel LNDB-2 Instantaneous (kW)', 1),
 ('225 KVA Xfmr - Panel LNDB-2 (kWh)', 1),
 ('225 KVA Xfmr - Panel LNDB-2 Max (kW)', 1),
 ('225 KVA Xfmr - Panel LNDB-2 Min (kW)', 1),
 (' 3-Ph Max Avg Demand (kVAR)', 1),
 (' 3-Ph Max Avg Demand (kVAR).1', 1),
 (' 3-Ph Min Avg Demand (kVAR)', 1),
 (' 3-Ph Min Avg Demand (kVAR).1', 1),
 (' 3-Ph total (kVA)', 1),
 (' 3-Ph total (kVAR)', 1),
 (' 3-Ph total (kW)', 1),
 ('Amps A (Amps)', 1),
 ('Amps B (Amps)', 1),
 ('Amps C (Amps)', 1),
 ('Annex Water70103387A Ave Rate (CFm)', 1),
 ('Annex Water70103387A Instantaneous (CFm)', 1),
 ('Annex Water70103387A Max (CFm)', 1),
 ('Annex Water70103387A Min (CFm)', 1),
 ('Annex Water 70103388A  Top Ave Rate (CFm)', 1),
 ('Annex Water 70103388A  Top Instantaneous (CFm)', 1),
 ('Annex Water 70103388A  Top Max (CFm)', 1),
 ('Annex Water 70103388A  Top Min (CFm)', 1),
 ('Apparent Power (kVA)', 1),
 (' Average (Amps)', 1),
 (' Average (Amps).1', 1),
 (' Average (Amps).2', 1),
 (' Average (kVA)', 1),
 (' Average (kVAR)', 1),
 (' Average (kVAR).1', 1),
 (' Average (kW)', 1),
 (' Average (kW).1', 1),
 ('BARROWS MAIN ELECTRIC Demand (kW)', 1),
 ('BARROWS MAIN ELECTRIC Instantaneous (kW)', 1),
 ('BARROWS MAIN ELECTRIC (kWh)', 1),
 ('BARROWS MAIN ELECTRIC Max (kW)', 1),
 ('BARROWS MAIN ELECTRIC Min (kW)', 1),
 ('Boalt Condensate Ave Rate (Gpm)', 1),
 ('Boalt Condensate (Gallons)', 1),
 ('Boalt Condensate Instantaneous (Gpm)', 1),
 ('Boalt Condensate Max (Gpm)', 1),
 ('Boalt Condensate Min (Gpm)', 1),
 ('Boalt Water 70144067 Ave Rate (CFm)', 1),
 ('Boalt Water 70144067 Instantaneous (CFm)', 1),
 ('Boalt Water 70144067 Max (CFm)', 1),
 ('Boalt Water 70144067 Min (CFm)', 1),
 ('Boalt Water 70249386 Ave Rate (CFm)', 1),
 ('Boalt Water 70249386 Ave Rate (Gpm)', 1),
 ('Boalt Water 70249386 (Gallons)', 1),
 ('Boalt Water 70249386 Instantaneous (CFm)', 1),
 ('Boalt Water 70249386 Instantaneous (Gpm)', 1),
 ('Boalt Water 70249386 Max (CFm)', 1),
 ('Boalt Water 70249386 Max (Gpm)', 1),
 ('Boalt Water 70249386 Min (CFm)', 1),
 ('Boalt Water 70249386 Min (Gpm)', 1),
 ('Building Steam Meter (Lbs)', 1),
 ('Condensate Meter Ave Rate (Gpm)', 1),
 ('Condensate Meter (Gallons)', 1),
 ('Condensate Meter Instantaneous (Gpm)', 1),
 ('Condensate Meter Max (Gpm)', 1),
 ('Condensate Meter Min (Gpm)', 1),
 ('CT Bypass Water Meter Ave Rate (Gpm)', 1),
 ('CT Bypass Water Meter (Gallons)', 1),
 ('CT Bypass Water Meter Instantaneous (Gpm)', 1),
 ('CT Bypass Water Meter Max (Gpm)', 1),
 ('CT Bypass Water Meter Min (Gpm)', 1),
 ('Current A (Amps)', 1),
 ('Current (Amps)', 1),
 ('Current B (Amps)', 1),
 ('Current C (Amps)', 1),
 ('Current phase A (Amps)', 1),
 ('Current phase B (Amps)', 1),
 ('Current phase C (Amps)', 1),
 (' Delivered (kWh)', 1),
 ('Demand A (kW)', 1),
 ('Demand Apparent (kVA)', 1),
 ('Demand B (kW)', 1),
 ('Demand C (kW)', 1),
 ('Demand (kW)', 1),
 ('Demand Max (kW)', 1),
 ('Demand Min (kW)', 1),
 ('Dryers Condensate Meter Ave Rate (Gpm)', 1),
 ('Dryers Condensate Meter (Gallons)', 1),
 ('Dryers Condensate Meter Instantaneous (Gpm)', 1),
 ('Dryers Condensate Meter Max (Gpm)', 1),
 ('Dryers Condensate Meter Min (Gpm)', 1),
 ('EAL Steam Meter (Lbs)', 1),
 ('East Condensate Meter Ave Rate (Gpm)', 1),
 ('East Condensate Meter (Gal)', 1),
 ('East Condensate Meter Instantaneous (Gpm)', 1),
 ('East Condensate Meter Max (Gpm)', 1),
 ('East Condensate Meter Min (Gpm)', 1),
 ('Edwards Track Irrigation Meter Ave Rate (Gpm)', 1),
 ('Edwards Track Irrigation Meter (Gallons)', 1),
 ('Edwards Track Irrigation Meter Instantaneous (Gpm)', 1),
 ('Edwards Track Irrigation Meter Max (Gpm)', 1),
 ('Edwards Track Irrigation Meter Min (Gpm)', 1),
 ('Electric Main #1 (#...213) Demand (kW)', 1),
 ('Electric Main#1 (#...213) Demand (kW)', 1),
 ('Electric Main#1 (#...213) Instantaneous (kW)', 1),
 ('Electric Main #1 (#...213) (kWh)', 1),
 ('Electric Main#1 (#...213) (kWh)', 1),
 ('Electric Main#1 (#...213) Max (kW)', 1),
 ('Electric Main#1 (#...213) Min (kW)', 1),
 ('Electric Main #1 (#...213) Runtime (seconds)', 1),
 ('Electric Main #2 (#...378) Demand (kW)', 1),
 ('Electric Main#2 (#...378) Demand (kW)', 1),
 ('Electric Main#2 (#...378) Instantaneous (kW)', 1),
 ('Electric Main #2 (#...378) (kWh)', 1),
 ('Electric Main#2 (#...378) (kWh)', 1),
 ('Electric Main#2 (#...378) Max (kW)', 1),
 ('Electric Main#2 (#...378) Min (kW)', 1),
 ('Electric Main #2 (#...378) Runtime (seconds)', 1),
 ('Electric MB01 Demand (kW)', 1),
 ('Electric MB01 Instantaneous (kW)', 1),
 ('Electric MB01 (kWh)', 1),
 ('Electric MB01 Max (kW)', 1),
 ('Electric MB01 Min (kW)', 1),
 ('Electric MB02 Demand (kW)', 1),
 ('Electric MB02 Instantaneous (kW)', 1),
 ('Electric MB02 (kWh)', 1),
 ('Electric MB02 Max (kW)', 1),
 ('Electric MB02 Min (kW)', 1),
 ('EMON Meter Demand (W)', 1),
 ('EMON Meter Instantaneous (W)', 1),
 ('EMON Meter Max (W)', 1),
 ('EMON Meter Min (W)', 1),
 ('EMON Meter (Wh)', 1),
 ('Energy A Net (kWh)', 1),
 ('Energy Apparent A (kVAh)', 1),
 ('Energy Apparent B (kVAh)', 1),
 ('Energy Apparent C (kVAh)', 1),
 ('Energy Apparent Sum (kVAh)', 1),
 ('Energy B Net (kWh)', 1),
 ('Energy C Net (kWh)', 1),
 ('Energy Consumption (kWh)', 1),
 ('Energy (kWh)', 1),
 ('Energy Neg A (kWh)', 1),
 ('Energy Neg B (kWh)', 1),
 ('Energy Neg C (kWh)', 1),
 ('Energy Neg Sum (kWh)', 1),
 ('Energy Neg Sum NR (kWh)', 1),
 ('Energy Pos A (kWh)', 1),
 ('Energy Pos B (kWh)', 1),
 ('Energy Pos C (kWh)', 1),
 ('Energy Pos Sum (kWh)', 1),
 ('Energy Pos Sum NR (kWh)', 1),
 ('Energy Reactive A (kVARh)', 1),
 ('Energy Reactive B (kVARh)', 1),
 ('Energy Reactive C (kVARh)', 1),
 ('Energy Reactive Sum (kVARh)', 1),
 ('Energy Sum (kWh)', 1),
 ('Energy Sum NR (kWh)', 1),
 ('Eshleman Main Water Meter Ave Rate (Gpm)', 1),
 ('Eshleman Main Water Meter (Gallons)', 1),
 ('Eshleman Main Water Meter Instantaneous (Gpm)', 1),
 ('Eshleman Main Water Meter Max (Gpm)', 1),
 ('Eshleman Main Water Meter Min (Gpm)', 1),
 ('Fire Pump Meter Demand (kW)', 1),
 ('Fire Pump Meter Instantaneous (kW)', 1),
 ('Fire Pump Meter (KWH)', 1),
 ('Fire Pump Meter Max (kW)', 1),
 ('Fire Pump Meter Min (kW)', 1),
 ('FrameSize (Amps)', 1),
 ('Freq (Hz)', 1),
 ('Freq mn (Hz)', 1),
 ('Freq mx (Hz)', 1),
 ('Frequency (Hz)', 1),
 ('Gas 61466562 Ave Rate (CFm)', 1),
 ('Gas 61466562 Instantaneous (CFm)', 1),
 ('Gas 61466562 Max (CFm)', 1),
 ('Gas 61466562 Min (CFm)', 1),
 ('Gas Meter Ave Rate (CFm)', 1),
 ('Gas Meter Instantaneous (CFm)', 1),
 ('Gas Meter Max (CFm)', 1),
 ('Gas Meter Min (CFm)', 1),
 ('Gilman Water 14458575 Ave Rate (CFm)', 1),
 ('Gilman Water 14458575 Instantaneous (CFm)', 1),
 ('Gilman Water 14458575 Max (CFm)', 1),
 ('Gilman Water 14458575 Min (CFm)', 1),
 ('Gilman Water 14458576 Ave Rate (CFm)', 1),
 ('Gilman Water 14458576 Instantaneous (CFm)', 1),
 ('Gilman Water 14458576 Max (CFm)', 1),
 ('Gilman Water 14458576 Min (CFm)', 1),
 ('Haas Pavilion Main Electric Demand (kW)', 1),
 ('Haas Pavilion Main Electric Instantaneous (kW)', 1),
 ('Haas Pavilion Main Electric (KWH)', 1),
 ('Haas Pavilion Main Electric Max (kW)', 1),
 ('Haas Pavilion Main Electric Min (kW)', 1),
 ('Hargrove Main Electric Demand (kW)', 1),
 ('Hargrove Main Electric Instantaneous (kW)', 1),
 ('Hargrove Main Electric (KWH)', 1),
 ('Hargrove Main Electric Max (kW)', 1),
 ('Hargrove Main Electric Min (kW)', 1),
 ('Hesse Obrien Water Meter 026 Ave Rate (CFm)', 1),
 ('Hesse Obrien Water Meter 026 Instantaneous (CFm)', 1),
 ('Hesse Obrien Water Meter 026 Max (CFm)', 1),
 ('Hesse Obrien Water Meter 026 Min (CFm)', 1),
 ('I1 Primary (Amps)', 1),
 ('I1 Secondary (Amps)', 1),
 ('I2 Primary (Amps)', 1),
 ('I2 Secondary (Amps)', 1),
 ('I3 Primary (Amps)', 1),
 ('I3 Secondary (Amps)', 1),
 ('I4 (Amps)', 1),
 ('Ia (A)', 1),
 ('I a (Amps)', 1),
 ('I a demand (Amps)', 1),
 ('I a peak demand (Amps)', 1),
 ('I ave (Amps)', 1),
 ('I ave mn (Amps)', 1),
 ('I avg mx (Amps)', 1),
 ('I AVG Primary (Amps)', 1),
 ('Ib (A)', 1),
 ('I b (Amps)', 1),
 ('I b demand (Amps)', 1),
 ('I b peak demand (Amps)', 1),
 ('Ic (A)', 1),
 ('I c (Amps)', 1),
 ('I c demand (Amps)', 1),
 ('I c peak demand (Amps)', 1),
 ('I demand (Amps)', 1),
 ('I peak demand (Amps)', 1),
 ('Irrigation Meter Ave Rate (Gpm)', 1),
 ('Irrigation Meter (Gallons)', 1),
 ('Irrigation Meter Instantaneous (Gpm)', 1),
 ('Irrigation Meter Max (Gpm)', 1),
 ('Irrigation Meter Min (Gpm)', 1),
 ('Irrigation Water 606 Ave Rate (CFm)', 1),
 ('Irrigation Water 606 Instantaneous (CFm)', 1),
 ('Irrigation Water 606 Max (CFm)', 1),
 ('Irrigation Water 606 Min (CFm)', 1),
 ('Irrigation Water ABADBECH Ave Rate (Gpm)', 1),
 ('Irrigation Water ABADBECH (Gallons)', 1),
 ('Irrigation Water ABADBECH Instantaneous (Gpm)', 1),
 ('Irrigation Water ABADBECH Max (Gpm)', 1),
 ('Irrigation Water ABADBECH Min (Gpm)', 1),
 ('Irrigation Water Ave Rate (Gpm)', 1),
 ('Irrigation Water (Gallons)', 1),
 ('Irrigation Water Instantaneous (Gpm)', 1),
 ('Irrigation Water Max (Gpm)', 1),
 ('Irrigation Water Min (Gpm)', 1),
 ('kVA a (kVA)', 1),
 ('kVA b (kVA)', 1),
 ('kVA c (kVA)', 1),
 ('kVA demand (kVA)', 1),
 ('KVA Demand (kVA)', 1),
 ('kVAh del+rec (kVAh)', 1),
 ('kVAh (kVAh)', 1),
 ('KVAH Total (kVAh)', 1),
 ('kVA peak demand (kVA)', 1),
 ('KVA Peak Demand (kVA)', 1),
 ('kVAR a (kVAR)', 1),
 ('kVAR b (kVAR)', 1),
 ('kVAR c (kVAR)', 1),
 ('kVAR demand (kVAR)', 1),
 ('KVAR Demand (kVAR)', 1),
 ('kVARh del (kVARh)', 1),
 ('KVARh Del (kVARh)', 1),
 ('kVARh del+rec (kVARh)', 1),
 ('kVARh del-rec (kVARh)', 1),
 ('kVARh rec (kVARh)', 1),
 ('KVARh Rec (kVARh)', 1),
 ('KVARh Total (kVARh)', 1),
 ('kVAR peak demand (kVAR)', 1),
 ('KVAR Peak Demand (kVAR)', 1),
 ('kVAR td (kVAR)', 1),
 ('kVAR td mx (kVAR)', 1),
 ('kVAR total (kVAR)', 1),
 ('KVAR Total (kVAR)', 1),
 ('kVAR tot (kVAR)', 1),
 ('kVAR tot mx (kVAR)', 1),
 ('kVA td (kVA)', 1),
 ('kVA td mx (kVA)', 1),
 ('kVA total (kVA)', 1),
 ('kVA tot (kVA)', 1),
 ('kVA tot mx (kVA)', 1),
 ('kW a (kW)', 1),
 ('kW b (kW)', 1),
 ('kW c (kW)', 1),
 ('kW demand (kW)', 1),
 ('kW Demand (kW)', 1),
 ('kWh a del (kWh)', 1),
 ('kWh a rec (kWh)', 1),
 ('kWh b del (kWh)', 1),
 ('kWh b rec (kWh)', 1),
 ('kWh c del (kWh)', 1),
 ('kWh c rec (kWh)', 1),
 ('kWh del (kWh)', 1),
 ('kWh Del (kWh)', 1),
 ('kWh del+rec (kWh)', 1),
 ('kWh del-rec (kWh)', 1),
 ('kWh rec (kWh)', 1),
 ('KWh Rec (kWh)', 1),
 ('kWh Total (kWh)', 1),
 ('kW peak demand (kW)', 1),
 ('kW Peak Demand (kW)', 1),
 ('kW td (kW)', 1),
 ('kW td mx (kW)', 1),
 ('kW total (kW)', 1),
 ('kW Total (kW)', 1),
 ('kW tot (kW)', 1),
 ('kW tot mx (kW)', 1),
 ('Large Gas 497697 Ave Rate (CFm)', 1),
 ('Large Gas 497697 (CF)', 1),
 ('Large Gas 497697 Instantaneous (CFm)', 1),
 ('Large Gas 497697 Max (CFm)', 1),
 ('Large Gas 497697 Min (CFm)', 1),
 ('Line Frequency (Hz)', 1),
 (' Line to Line (Volts)', 1),
 (' Line to Neutral (Volts)', 1),
 ('Main # 1 Demand (kW)', 1),
 ('Main # 1 Instantaneous (kW)', 1),
 ('Main # 1 (KWH)', 1),
 ('Main # 1 Max (kW)', 1),
 ('Main # 1 Min (kW)', 1),
 ('Main # 2 Demand (kW)', 1),
 ('Main # 2 Instantaneous (kW)', 1),
 ('Main # 2 (KWH)', 1),
 ('Main # 2 Max (kW)', 1),
 ('Main # 2 Min (kW)', 1),
 ('Main # 3 Demand (kW)', 1),
 ('Main # 3 Instantaneous (kW)', 1),
 ('Main # 3 (KWH)', 1),
 ('Main # 3 Max (kW)', 1),
 ('Main # 3 Min (kW)', 1),
 ('Main # 4 Demand (kW)', 1),
 ('Main # 4 Instantaneous (kW)', 1),
 ('Main # 4 (KWH)', 1),
 ('Main # 4 Max (kW)', 1),
 ('Main # 4 Min (kW)', 1),
 ('Main Electrical Meter Demand (kW)', 1),
 ('Main Electrical Meter Instantaneous (kW)', 1),
 ('Main Electrical Meter (kWH)', 1),
 ('Main Electrical Meter Max (kW)', 1),
 ('Main Electrical Meter Min (kW)', 1),
 ('Main Electric Demand (kW)', 1),
 ('Main Electric Instantaneous (kW)', 1),
 ('Main Electric (kWh)', 1),
 ('Main Electric Max (kW)', 1),
 ('Main Electric Meter 1 Demand (kW)', 1),
 ('Main Electric Meter 1 Instantaneous (kW)', 1),
 ('Main Electric Meter 1 (kWh)', 1),
 ('Main Electric Meter 1 Max (kW)', 1),
 ('Main Electric Meter 1 Min (kW)', 1),
 ('Main Electric Meter 2 Demand (kW)', 1),
 ('Main Electric Meter 2 Instantaneous (kW)', 1),
 ('Main Electric Meter 2 (kWh)', 1),
 ('Main Electric Meter 2 Max (kW)', 1),
 ('Main Electric Meter 2 Min (kW)', 1),
 ('Main Electric Meter Demand (kW)', 1),
 ('Main Electric Meter Instantaneous (kW)', 1),
 ('Main Electric Meter (kWh)', 1),
 ('Main Electric Meter (kWH)', 1),
 ('Main Electric Meter Max (kW)', 1),
 ('Main Electric Meter Min (kW)', 1),
 ('Main Electric Min (kW)', 1),
 ('Main Gas Meter Ave Rate (CFm)', 1),
 ('Main Gas Meter Instantaneous (CFm)', 1),
 ('Main Gas Meter Max (CFm)', 1),
 ('Main Gas Meter Min (CFm)', 1),
 ('Main Water Meter 279 Ave Rate (CFm)', 1),
 ('Main Water Meter 279 Instantaneous (CFm)', 1),
 ('Main Water Meter 279 Max (CFm)', 1),
 ('Main Water Meter 279 Min (CFm)', 1),
 ('Main Water Meter Ave Rate (CFm)', 1),
 ('Main Water Meter Ave Rate (Gpm)', 1),
 ('Main Water Meter (Gallons)', 1),
 ('Main Water Meter Instantaneous (CFm)', 1),
 ('Main Water Meter Instantaneous (Gpm)', 1),
 ('Main Water Meter Max (CFm)', 1),
 ('Main Water Meter Max (Gpm)', 1),
 ('Main Water Meter Min (CFm)', 1),
 ('Main Water Meter Min (Gpm)', 1),
 (' Max Avg Demand (Amps)', 1),
 (' Max Avg Demand (Amps).1', 1),
 (' Max Avg Demand (Amps).2', 1),
 (' Max Avg Demand (kVA)', 1),
 (' Max Avg Demand (kW)', 1),
 (' Max Avg Demand (kW).1', 1),
 (' Max (Hz)', 1),
 (' Max (Volts)', 1),
 (' Max (Volts).1', 1),
 (' Max (Volts).2', 1),
 (' Max (Volts).3', 1),
 (' Max (Volts).4', 1),
 (' Max (Volts).5', 1),
 ('Meter 4 (Units)', 1),
 ('Meter 5 (Units)', 1),
 ('Meter 6 (Units)', 1),
 ('Meter 7 (Units)', 1),
 ('Meter 8 (Units)', 1),
 (' Min Avg Demand (Amps)', 1),
 (' Min Avg Demand (Amps).1', 1),
 (' Min Avg Demand (Amps).2', 1),
 (' Min Avg Demand (kVA)', 1),
 (' Min Avg Demand (kW)', 1),
 (' Min Avg Demand (kW).1', 1),
 (' Min (Hz)', 1),
 (' Min (Volts)', 1),
 (' Min (Volts).1', 1),
 (' Min (Volts).2', 1),
 (' Min (Volts).3', 1),
 (' Min (Volts).4', 1),
 (' Min (Volts).5', 1),
 ('ML King Main Water Meter Ave Rate (Gpm)', 1),
 ('ML King Main Water Meter (Gallons)', 1),
 ('ML King Main Water Meter Instantaneous (Gpm)', 1),
 ('ML King Main Water Meter Max (Gpm)', 1),
 ('ML King Main Water Meter Min (Gpm)', 1),
 ('ML King Water (test) Ave Rate (Gpm)', 1),
 ('ML King Water (test) (Gallons)', 1),
 ('ML King Water (test) Instantaneous (Gpm)', 1),
 ('ML King Water (test) Max (Gpm)', 1),
 ('ML King Water (test) Min (Gpm)', 1),
 ('MSA Main Up to 12/12/14 Demand (kW)', 1),
 ('MSA Main Up to 12/12/14 Instantaneous (kW)', 1),
 ('MSA Main Up to 12/12/14 (kWh)', 1),
 ('MSA Main Up to 12/12/14 Max (kW)', 1),
 ('MSA Main Up to 12/12/14 Min (kW)', 1),
 ('MSB1 Electric  (208/120 v) Demand (kW)', 1),
 ('MSB1 Electric  (208/120 v) Instantaneous (kW)', 1),
 ('MSB1 Electric  (208/120 v) (KWH)', 1),
 ('MSB1 Electric  (208/120 v) Max (kW)', 1),
 ('MSB1 Electric  (208/120 v) Min (kW)', 1),
 ('MSB2 Electric  (480/277 v) Demand (kW)', 1),
 ('MSB2 Electric  (480/277 v) Instantaneous (kW)', 1),
 ('MSB2 Electric  (480/277 v) (KWH)', 1),
 ('MSB2 Electric  (480/277 v) Max (kW)', 1),
 ('MSB2 Electric  (480/277 v) Min (kW)', 1),
 ('MSB Main Demand (kW)', 1),
 ('MSB Main Instantaneous (kW)', 1),
 ('MSB Main (kWh)', 1),
 ('MSB Main Max (kW)', 1),
 ('MSB Main Min (kW)', 1),
 (' Negative (kVARh)', 1),
 (' Net (kVARh)', 1),
 (' Net (kWh)', 1),
 ('Neutral Current (Amps)', 1),
 ('North Steam Flow (lbs)', 1),
 ('North Steam Flow (Lbs)', 1),
 ('North Tower Water 916 Ave Rate (Gpm)', 1),
 ('North Tower Water 916 (Gallons)', 1),
 ('North Tower Water 916 Instantaneous (Gpm)', 1),
 ('North Tower Water 916 Max (Gpm)', 1),
 ('North Tower Water 916 Min (Gpm)', 1),
 ('Peak Demand (kW)', 1),
 ('Peak Reactive Power (kVAR)', 1),
 (' Phase A Current (Degrees)', 1),
 (' Phase B Current (Degrees)', 1),
 (' Phase C Current (Degrees)', 1),
 ('Pool Steam Meter (Lbs)', 1),
 (' Positive (kVARh)', 1),
 ('Power A (kW)', 1),
 ('Power Apparent A (kVA)', 1),
 ('Power Apparent B (kVA)', 1),
 ('Power Apparent C (kVA)', 1),
 ('Power Apparent Sum (kVA)', 1),
 ('Power B (kW)', 1),
 ('Power C (kW)', 1),
 ('PowerDemand (kW)', 1),
 ('Power Reactive A (kVAR)', 1),
 ('Power Reactive B (kVAR)', 1),
 ('Power Reactive C (kVAR)', 1),
 ('Power Reactive Sum (kVAR)', 1),
 ('Power Sum (kW)', 1),
 ('Present Demand (kW)', 1),
 ('Present Demand (subinterval) (kW)', 1),
 ('Present Reactive Power (kVAR)', 1),
 ('Present Reactive Power (subinterval) (kVAR)', 1),
 ('Pulse #4 Runtime (seconds)', 1),
 ('Rain Water Meter Ave Rate (Gpm)', 1),
 ('Rain Water Meter (Gallons)', 1),
 ('Rain Water Meter Instantaneous (Gpm)', 1),
 ('Rain Water Meter Max (Gpm)', 1),
 ('Rain Water Meter Min (Gpm)', 1),
 ('Reactive Power (kVAR)', 1),
 ('Real Power (kW)', 1),
 ('Real Power phase A (kW)', 1),
 ('Real Power phase B (kW)', 1),
 ('Real Power phase C (kW)', 1),
 (' Received (kWh)', 1),
 ('RSF Irrigation Meter Ave Rate (Gpm)', 1),
 ('RSF Irrigation Meter (Gallons)', 1),
 ('RSF Irrigation Meter Instantaneous (Gpm)', 1),
 ('RSF Irrigation Meter Max (Gpm)', 1),
 ('RSF Irrigation Meter Min (Gpm)', 1),
 ('SDH Conductivity Meter Ave (uS)', 1),
 ('SDH Conductivity Meter Max (uS)', 1),
 ('SDH Conductivity Meter Min (uS)', 1),
 ('SDH Conductivity Meter (uS)', 1),
 ('SDH Steam (Lbs)', 1),
 ('Simon Condensate Ave Rate (Gpm)', 1),
 ('Simon Condensate (Gallons)', 1),
 ('Simon Condensate Instantaneous (Gpm)', 1),
 ('Simon Condensate Max (Gpm)', 1),
 ('Simon Condensate Min (Gpm)', 1),
 ('Simon Water 70249385 Ave Rate (CFm)', 1),
 ('Simon Water 70249385 Instantaneous (CFm)', 1),
 ('Simon Water 70249385 Max (CFm)', 1),
 ('Simon Water 70249385 Min (CFm)', 1),
 ('Simon Water 70249387 Ave Rate (CFm)', 1),
 ('Simon Water 70249387 Instantaneous (CFm)', 1),
 ('Simon Water 70249387 Max (CFm)', 1),
 ('Simon Water 70249387 Min (CFm)', 1),
 ('Simpson Water 12204970L Ave Rate (CFm)', 1),
 ('Simpson Water 12204970L Instantaneous (CFm)', 1),
 ('Simpson Water 12204970L Max (CFm)', 1),
 ('Simpson Water 12204970L Min (CFm)', 1),
 ('Simpson Water 12204970S Ave Rate (CFm)', 1),
 ('Simpson Water 12204970S Instantaneous (CFm)', 1),
 ('Simpson Water 12204970S Max (CFm)', 1),
 ('Simpson Water 12204970S Min (CFm)', 1),
 ('Simpson Water 12204971L Ave Rate (CFm)', 1),
 ('Simpson Water 12204971L Instantaneous (CFm)', 1),
 ('Simpson Water 12204971L Max (CFm)', 1),
 ('Simpson Water 12204971L Min (CFm)', 1),
 ('Simpson Water 12204971S Ave Rate (CFm)', 1),
 ('Simpson Water 12204971S Instantaneous (CFm)', 1),
 ('Simpson Water 12204971S Max (CFm)', 1),
 ('Simpson Water 12204971S Min (CFm)', 1),
 ('Small Gas 98Z682247 Ave Rate (CFm)', 1),
 ('Small Gas 98Z682247 Instantaneous (CFm)', 1),
 ('Small Gas 98Z682247 Max (CFm)', 1),
 ('Small Gas 98Z682247 Min (CFm)', 1),
 ('South Steam Flow (lbs)', 1),
 ('South Steam Flow (Lbs)', 1),
 ('Steam Ave (Lbs)', 1),
 ('Steam Condensate Ave Rate (Gpm)', 1),
 ('Steam Condensate (Gallons)', 1),
 ('Steam Condensate Instantaneous (Gpm)', 1),
 ('Steam Condensate Max (Gpm)', 1),
 ('Steam Condensate Meter Ave Rate (Gpm)', 1),
 ('Steam Condensate Meter (Gal)', 1),
 ('Steam Condensate Meter (Gallons)', 1),
 ('Steam Condensate Meter Instantaneous (Gpm)', 1),
 ('Steam Condensate Meter Max (Gpm)', 1),
 ('Steam Condensate Meter Min (Gpm)', 1),
 ('Steam Condensate Min (Gpm)', 1),
 ('Steam Flow (Lbs)', 1),
 ('Steam (Lbs)', 1),
 ('Steam Max (Lbs)', 1),
 ('Steam Meter Flow (Lbs)', 1),
 ('Steam Meter (Lbs)', 1),
 ('Steam Meter (Pounds)', 1),
 ('Steam Min (Lbs)', 1),
 ('Steam Runtime (seconds)', 1),
 ('Steam Totalizer (lbs)', 1),
 ('Steam Totalizer (Lbs)', 1),
 ('Steam Usage (Pounds)', 1),
 ('Sub 1 Main Meter Demand (kW)', 1),
 ('Sub 1 Main Meter Instantaneous (kW)', 1),
 ('Sub 1 Main Meter (kWh)', 1),
 ('Sub 1 Main Meter Max (kW)', 1),
 ('Sub 1 Main Meter Min (kW)', 1),
 ('Sub 2 Main Meter Demand (kW)', 1),
 ('Sub 2 Main Meter Instantaneous (kW)', 1),
 ('Sub 2 Main Meter (kWh)', 1),
 ('Sub 2 Main Meter Max (kW)', 1),
 ('Sub 2 Main Meter Min (kW)', 1),
 (' Total (kVAh)', 1),
 ('Total_kVA (kVA)', 1),
 (' Total (kVARh)', 1),
 ('Total_kVAR (kVAR)', 1),
 (' Total (kWh)', 1),

In [26]:
%%sql result_3c <<
WITH 
groupby AS
(SELECT class, COUNT(DISTINCT(units)) AS COUNT
FROM metadata
GROUP BY class),

max_value AS
(SELECT MAX(count)
    FROM groupby)
    
SELECT
    CASE WHEN max = 1 THEN true ELSE false END AS boolean
FROM max_value;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
1 rows affected.
Returning data to local variable result_3c

In [27]:
result_3c

[(True,)]

<!-- END QUESTION -->

<!--
BEGIN QUESTION
name: q3c
points: 1
-->

In [28]:
# Do not delete/edit this cell
result_3c.DataFrame().to_csv('results/result_3c.csv', index=False)

In [29]:
grader.check("q3c")

q3c results: All test cases passed!

<!-- BEGIN QUESTION -->

### Question 3d

Moving on, have a look at the `real_estate_metadata` table---starting with the distinct values in the `location` field! What do you notice about these values?

<!--
BEGIN QUESTION
name: q3d
manual: true
points: 0
-->

In [30]:
%%sql
SELECT DISTINCT location
FROM real_estate_metadata;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
15 rows affected.

[('LOS ANGELES',),
 ('FRANCISC O',),
 ('SYSTEMWI DE',),
 ('SAN DSAIENG O',),
 ('FRANCISC SOAN',),
 ('SANTA CRUZ',),
 ('AG FIELD STAT',),
 ('IRVINE',),
 ('RIVERSIDE',),
 ('BERKELEY',),
 ('SANTA BARBARA',),
 ('DAVIS',),
 ('FRANCISC OSAN',),
 ('MERCED',),
 ('SAN DIEGO',)]

I notice that some of the locations appear to be misspelled. For instance, FRANCISC OSAN is not really a place.

<!-- END QUESTION -->



### Question 3e

It turns out this table was the result of an [OCR scan](https://en.wikipedia.org/wiki/Optical_character_recognition). We'll just clean up the `location` column for now, and leave you to imagine the effort to do a full cleanup of all columns.

To provide some useful utility functions, we have preloaded Postgres' extension packages for "fuzzy" string matching and trigrams for you. You can use any of the string functions in those packages if you like ([as documented here for fuzzystrmatch](https://www.postgresql.org/docs/current/fuzzystrmatch.html) or [here for pg_trgm](https://www.postgresql.org/docs/current/pgtrgm.html)).

We also created a lookup table of canonical names, `uc_locations`.

Now, using any of the string functions you like (or none at all!), write a SQL query that returns the columns `(building_name, address, location, clean_location)` where `clean_location` contains the best match from `uc_locations.loc_name`. You may find that you can't clean up everything with the string functions, so your view may have to include some specific logic for cases in the data that have to be handled "manually". You can choose to do this question in whatever manner you wish as long as your query does not use `CREATE TABLE`, `INSERT INTO`, or `UPDATE`.

In [31]:
%%sql
SELECT *
FROM uc_locations;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
12 rows affected.

[(1, 'AG FIELD STAT'),
 (2, 'BERKELEY'),
 (3, 'DAVIS'),
 (4, 'IRVINE'),
 (5, 'LOS ANGELES'),
 (6, 'MERCED'),
 (7, 'RIVERSIDE'),
 (8, 'SAN DIEGO'),
 (9, 'SAN FRANCISCO'),
 (10, 'SANTA BARBARA'),
 (11, 'SANTA CRUZ'),
 (12, 'SYSTEMWIDE')]

In [32]:
%%sql result_3e <<
WITH 
clean_1 AS (
SELECT a.building_name, a.address, a.location, b.loc_name AS clean_location1
FROM real_estate_metadata AS a LEFT JOIN uc_locations AS b
ON levenshtein(a.location, b.loc_name) < 3),

clean_2 AS (
SELECT  building_name, address, location,
    CASE 
    WHEN location = 'SAN DSAIENG O' THEN 'SAN DIEGO' 
    WHEN location = 'FRANCISC O' THEN 'SAN FRANCISCO'
    WHEN location = 'FRANCISC SOAN' THEN 'SAN FRANCISCO'
    WHEN location = 'FRANCISC OSAN' THEN 'SAN FRANCISCO'
    ELSE clean_location1
    END AS clean_location
FROM clean_1)

SELECT * FROM clean_2;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
5276 rows affected.
Returning data to local variable result_3e

In [33]:
# Do not delete/edit this cell
result_3e.DataFrame().sort_values(['clean_location', 'building_name', 'address']).iloc[::10].to_csv('results/result_3e.csv', index=False)

In [34]:
grader.check("q3e")

q3e results: All test cases passed!

## Question 4: Interpolating Missing Data
Real-world data, real-world problems. Our sensors should be reporting every 15 minutes, but you can be sure that we're missing some data. Here we will fix it. It's a bit more involved than what we looked at in class!

### Question 4a: Finding missing readings
In the `data` table, the `id` column identifies a unique sensor. Sensor readings should be recorded every 15 minutes from every sensor. Are we missing any readings, and if so which ones? We will focus on readings that are separated by at least 30 minutes or more; readings that are \[0-30) minutes apart are considered to be fine.

To answer this question you'll need to read up a bit on [SQL timestamps](https://www.postgresql.org/docs/current/datatype-datetime.html) and [Functions for manipulating datetime types](https://www.postgresql.org/docs/current/functions-datetime.html). Have a particular look at the following:
- The [date_trunc](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC) function will quantize times to the nearest unit of your choosing. E.g. to round the `time` field to the nearest minute you can say `date_trunc('minute', time)`. **You'll need to quantize to minutes right away before you worry about missing readings.**
- There are various ways to enter constant intervals of time as strings. E.g. a 30 minute interval can be written as `interval '30 minutes'` or `'30 minutes'::interval`. See [date/time input](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT) for more info.
- You can do arithmetic on date/time types [as documented here](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC). That will handle all the weird periodicities of clocks and calendars for you. Pay attention to the input and output types of these functions!
- Alternatively, the [EXTRACT](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT) function is sometimes handy. Note the special `EXTRACT(EPOCH FROM ...)` case. This converts a timestamp into an integer representing the number of seconds since midnight, 1/1/1970 (the dawn of [UNIX time](https://en.wikipedia.org/wiki/Unix_time)!)  You can do normal integer comparisons and arithmetic on the results.
- You will need to use the [lag](https://www.geeksforgeeks.org/postgresql-lag-function/) function as the window function.


Create a view called `gaps` that augments the `data` schema with three columns:
- `lagtime` is the quantized time of the previous reading for that sensor (relative to the current row for a particular row)
- `lagvalue` is the value of the previous reading for that sensor
- `timediff` is the difference in quantized time between this reading and the previous reading

The view should only contain rows where `timediff` is **greater than or equal to 30 minutes**.

In [35]:
%%sql result_4a <<
CREATE OR REPLACE VIEW gaps AS
WITH 
quan AS(
   SELECT *, date_trunc('minute', time) AS quan_time
    FROM data),

lags AS (
    SELECT *, LAG(quan_time, 1) OVER (PARTITION BY id ORDER BY time) AS lagtime, 
        LAG(value, 1) OVER (PARTITION BY id ORDER BY time) AS lagvalue
FROM quan),

diffs AS (
    SELECT *, quan_time - lagtime AS timediff
FROM lags)

SELECT id, time, value, lagtime, lagvalue, timediff  
FROM diffs
WHERE timediff >= '30 minutes'::interval;
        
SELECT * FROM gaps ORDER BY id, time LIMIT 10;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
Done.
10 rows affected.
Returning data to local variable result_4a

In [36]:
# Do not delete/edit this cell
result_4a.DataFrame().to_csv('results/result_4a.csv', index=False)

In [37]:
grader.check("q4a")

q4a results: All test cases passed!

### Question 4b: Creating tuples for the missing readings
Now we need to manufacture new tuples to fill in the gaps. For example, if you had a tuple from id `abc` timestamped at 1PM today and the next tuple in time from `abc` was timestamped at 1:45PM, you'll need to manufacture two new tuples with id `abc` and `NULL` values: one timestamped at 1:15PM and another timestamped at 1:30PM. We will worry about replacing the `NULL` values in the next step.

To manufacture tuples not related to stored data in the database, we'll need to use a *table-valued function* as we did in lecture 12 (when we manufactured data from a normal distribution). The table-valued function we want here is `generate_series` [(documented here)](https://www.postgresql.org/docs/current/functions-srf.html), which we will use to generate *and sequentially timestamp* the right number of tuples to match the number of tuples we found missing.

To get a feel for `generate_series`, consider the following simple query that generates a table of integers with intervals of size 3 between them.

In [38]:
%%sql
SELECT *
  FROM generate_series(0, 100, 15);

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
7 rows affected.

[(0,), (15,), (30,), (45,), (60,), (75,), (90,)]

Now, we can use `generate_series` in a `LATERAL JOIN` query: for each tuple on the left of the `LATERAL` it will produce a series based on the values of that tuple. So for example, we can generate 2 tuples for each tuple of `uc_locations` as follows:

Notice how the 2 values it generates are the length of the `loc_name`, and the length + 2. You might want to play with the query above to make sure you understand the documentation for `generate_series` and `LATERAL`.

Ok, on to your task!

Create a view `complete` that contains the tuples from `data` as well as new tuples that fill in any gaps greater than or equal to 30 minutes. Each gap should be filled by adding tuples in increments of 15 minutes from the *start* of the gap, **with `NULL` as the value**. You probably want to use your `gaps` view as well as `generate_series` to do this!

**Hint:** the lower and upper bounds in generate_series (in pseudocode) should be `(lagtime + 15 minutes, time - 15 minutes)`.

In [39]:
%%sql result_4b <<
CREATE OR REPLACE VIEW complete AS

SELECT g.id, newal AS time, NULL AS value
  FROM gaps g,
    LATERAL generate_series(g.lagtime + '15 minutes'::interval, g.time - '15 minutes'::interval, '15 minutes'::interval) AS newal
         
        UNION 
        
SELECT id, time, value
FROM data;

        
        
SELECT * FROM complete ORDER BY id, time LIMIT 100;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
Done.
100 rows affected.
Returning data to local variable result_4b

In [40]:
# Do not delete/edit this cell
result_4b.DataFrame().to_csv('results/result_4b.csv', index=False)

In [41]:
grader.check("q4b")

q4b results: All test cases passed!

### Question 4c: Linear Interpolation
*Note: If you struggled with the previous subparts of this problem, you can use our table `complete_provided` instead of your `complete` table in this subpart.*

Now, given the `complete` view or the `complete_provided` table, the remaining task is to do linear interpolation to fill in the missing values we manufactured in Step 2. We have code from **this semester's** Lecture 14 (Data Cleaning) we can reuse here! In particular, your database already includes the UDA `coalesce_agg` we used in lecture (you can use it directly, there's no need to redefine it).

But note that in Lecture 14's example of linear interpolation we had a field called `entry_rank` that was used to order *all* the records in the table. By contrast, here the ordering we care about is the series of `time` for each sensor `id` *independently*. You will need to make minor changes to adapt the linear interpolation code from class to work here.

Create a view `likely_data` that contains all the tuples from `complete`, with an additional column called `interpolated` that contains a copy of `value` if it is non-NULL, otherwise an interpolated value based on linear interpolation *per sensor id over time*. Please **retain all additional columns created from forward and backward passes** (there should be 10 columns in the view - the order of the columns does not matter.) The three cells below correspond to the forward, backward, and final passes from lecture.

In [42]:
%%sql
CREATE OR REPLACE VIEW forward AS

SELECT *,
    SUM(CASE WHEN value IS NULL THEN 0 ELSE 1 END)
        OVER (PARTITION BY id ORDER BY time) AS run,
    coalesce_agg(value) OVER (PARTITION BY id ORDER BY time) AS run_start,
    CASE WHEN value IS NULL
        THEN lead(value, 1) OVER (PARTITION BY id ORDER BY time)
        ELSE NULL
    END AS nextval
FROM complete_provided;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
Done.

[]

In [43]:
%%sql
CREATE OR REPLACE VIEW backward AS

SELECT *,
        CASE WHEN value IS NOT NULL THEN value
            ELSE coalesce_agg(nextval) OVER (PARTITION BY id, run ORDER BY time DESC)
        END AS run_end,
        count(*) OVER (PARTITION BY id, run) AS run_size,
        count(*) OVER (PARTITION BY id, run ORDER BY time) AS run_rank
FROM forward;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
Done.

[]

In [44]:
%%sql result_4c <<
CREATE OR REPLACE VIEW likely_data AS

SELECT *, 
       run_start + (run_rank-1)*((run_end-run_start)/(run_size))
         AS interpolated
FROM backward;

SELECT * FROM likely_data WHERE run_size > 2 ORDER BY id, time LIMIT 100;

   postgresql://jovyan@127.0.0.1:5432/template1
 * postgresql://jovyan@127.0.0.1:5432/ucb_buildings
Done.
100 rows affected.
Returning data to local variable result_4c

In [45]:
# Do not delete/edit this cell
result_4c.DataFrame().to_csv('results/result_4c.csv', index=False)

In [46]:
grader.check("q4c")

q4c results: All test cases passed!

## Congratulations! You have finished Project 3.

Run the following cell to zip and download the results of your queries. You will also need to run the export cell at the end of the notebook.

**For submission on Gradescope, you will need to submit BOTH the proj3.zip file genreated by the export cell and the results.zip file generated by the following cell.**

**Common submission issues:** You MUST submit the generated zip files (not folders) to the autograder. However, Safari is known to automatically unzip files upon downloading. You can fix this by going into Safari preferences, and deselect the box with the text "Open safe files after downloading" under the "General" tab. If you experience issues with downloading via clicking on the link, you can also navigate to the project 3 directory within JupyterHub (remove `proj3.ipynb` from the url), and manually download the generated zip files. Please post on Ed if you encounter any other submission issues.

In [47]:
from IPython.display import display, FileLink

!zip -r results.zip results
results_file = FileLink('./results.zip', result_html_prefix="Click here to download: ")
display(results_file)

  adding: results/ (stored 0%)
  adding: results/result_1b.csv (deflated 78%)
  adding: results/result_1c.csv (deflated 58%)
  adding: results/result_2a.csv (deflated 92%)
  adding: results/result_2b.csv (deflated 92%)
  adding: results/result_3b.csv (deflated 6%)
  adding: results/result_3c.csv (stored 0%)
  adding: results/result_3e.csv (deflated 76%)
  adding: results/result_4a.csv (deflated 73%)
  adding: results/result_4b.csv (deflated 90%)
  adding: results/result_4c.csv (deflated 84%)

/home/jovyan/fa22/proj/proj3/results.zip

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [48]:
grader.check_all()

q1b results: All test cases passed!

q1c results: All test cases passed!

q2a results: All test cases passed!

q2b results: All test cases passed!

q3b results: All test cases passed!

q3c results: All test cases passed!

q3e results: All test cases passed!

q4a results: All test cases passed!

q4b results: All test cases passed!

q4c results: All test cases passed!

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [49]:
# Save your notebook first, then run this cell to export your submission.
grader.export()